repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    - id: check-json
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: detect-private-key

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.2
    hooks:
    - id: flake8
      exclude: ^(Tests|Examples|Docs)/
      args: ['--max-line-length=120']

  -   repo: https://github.com/awebdeveloper/pre-commit-prettier
      rev: master
      hooks:
      -   id: prettier
          name: prettier qml plugin
          additional_dependencies:
            - prettier@1.19.1
            - "prettier-plugin-qml@0.10.2"
          files: \.qml$
          exclude: /Tests
