repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    - id: check-json
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: detect-private-key

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.2
    hooks:
    - id: flake8
      exclude: ^(Tests|Examples|Docs)/
      args: ['--max-line-length=120']

  - repo: https://github.com/awebdeveloper/pre-commit-prettier
    rev: master
    hooks:
    - id: prettier
      name: prettier qml plugin
      additional_dependencies:
      - prettier@1.19.1
      - "prettier-plugin-qml@0.10.2"
      files: \.qml$
      exclude: /Tests

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.1.1
    hooks:
    - id: seed-isort-config

  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
    - id: isort

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: 2.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
