name: CI - PIP

on: [push]

jobs:
  build:
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - uses: Gr1N/setup-poetry@v2
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
        poetry update
    - name: Test with tox
      run: |
        poetry build
        poetry run tox
      env:
        COVERAGE_FILE: $GITHUB_WORKSPACE/.coverage
    - name: Upload coverage
      uses: codecov/codecov-action@v1
    - name: Check Build
      run: |
        pip install twine
        python -m twine check dist/*
